name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      # Di-comment sementara karena runner ubuntu-latest bawaan GitHub Actions 
      # belum menginstal compiler Midnight (compactc) secara otomatis.
      # - name: Compile compact contract
      #   run: compact compile

      - name: Run test suite
        run: npm test
